apiVersion: v2
name: meteor-pipelines
description: a set of Tekton pipelines
icon: https://avatars.githubusercontent.com/u/33906690?v=4

type: application

version: 0.1.0
appVersion: "0.1.0"

sources: 
  - https://github.com/AICoE/aicoe-ci

keywords:
  - AICoE
  - Project Thoth
  - Open Data Hub
  - Operate First
  - OpenShift Pipelines 
  - Data Science 

maintainers:
  - email: goern@redhat.com
    name: Christoph GÃ¶rn 